export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST required' });
  if (!process.env.RESEND_API_KEY) return res.status(503).json({ error: 'Email export is not configured. Add RESEND_API_KEY and RESEARCH_FROM_EMAIL in Vercel Environment Variables, then redeploy.' });

  try {
    const { to, subject, event, query, answer, results = [] } = req.body || {};
    if (!to || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) return res.status(400).json({ error: 'A valid destination email is required.' });
    if (!results.length) return res.status(400).json({ error: 'No research results to export.' });

    const safe = (v='') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const items = results.slice(0,20).map((r,i) => `<article style="margin:0 0 24px;padding:16px;border:1px solid #ddd"><h3>${i+1}. ${safe(r.title)}</h3><p>${safe(r.content || '')}</p><p><strong>Fit:</strong> ${safe(r.fit || 'live')} ${r.fit ? '%' : ''}</p><p><a href="${safe(r.url)}">${safe(r.url)}</a></p></article>`).join('');
    const html = `<!doctype html><html><body style="font-family:Arial,sans-serif;color:#16181a;max-width:760px;margin:auto;padding:32px"><h1>${safe(event?.name || 'Event Growth OS research')}</h1><p><strong>${safe(event?.location || '')}</strong> · ${safe(event?.date || '')}</p><p>${safe(event?.audience || '')}</p><hr><h2>Research query</h2><p>${safe(query || '')}</p>${answer ? `<h2>Agent synthesis</h2><p>${safe(answer)}</p>` : ''}<h2>Live sources</h2>${items}<p style="color:#777;font-size:12px">Generated by Event Growth OS. Sources were fetched live; verify important claims at the original URLs.</p></body></html>`;

    const r = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${process.env.RESEND_API_KEY}` },
      body: JSON.stringify({
        from: process.env.RESEARCH_FROM_EMAIL || 'onboarding@resend.dev',
        to: [to],
        subject: subject || `Event Growth OS research — ${event?.name || 'Event research'}`,
        html
      })
    });
    const data = await r.json();
    if (!r.ok) return res.status(r.status).json({ error: data?.message || 'Email provider rejected the request', upstream: data });
    return res.status(200).json({ sent: true, id: data.id, to });
  } catch (error) {
    return res.status(500).json({ error: error?.message || 'Email export failed' });
  }
}
